//Batch 66
//Akshit Johry 2014A7PS077P
//Arpit Panda 2014A7PS114P


#include <stdio.h>
#include "parser1.c"
int main(int argc, char *argv[])
{
    struct tree_unit* root; 

    if(argc !=3){
		printf("Arguments number not as expected\n");
		return 0;
    }

    int choice;
    int compute3=0;
    
    printf("Press option for the defined task:\n");
    printf("1 : Remove comments and print the comment free code.\n");
    printf("2 : Print the token list generated by the lexer.\n");
    printf("3 : Parse to verify the syntactic correctness of the input source code.\n");
    printf("4 : Create Parse Tree\n");
    printf("0 : Exit.\n");
    scanf("%d",&choice);

    if(choice==1){
            printWithoutComments(argv[1]);

    }
    else if(choice==2)
    {
        file1_main(argv[1],1);
    }
    else if(choice==3)
    {

        parser_main(argv[1]);
		compute3=1;
    }
    else if(choice==4)
    {
	if(compute3==0){
	//printf("File not parsed yet\n");
	printf("File Parsed...\n");
	parser_main(argv[1]);
		compute3=1;

	}
        buildTreeFILE(argv[2]);


    }

    

  



    return 0;
}

